### PR TITLE
Add support for different SRP revisions (3, 6)

### PR DESCRIPTION
**Pull request by JustArchi**
This PR adds support for different SRP revisions - namely `3` and `6`, on top of existing `6a`.

The server that I'm working with supports only SRP in revision `6`. Using `6a` implementation of srp.net for it obviously generates invalid session, as the algorithm is different. However, it's quite simple to add missing support for revision `6`, which affects only how `K` is generated.

I tested SRP algorithm with revision `6` against the real server and it seems to be working properly. I've also added one unit test.

I didn't test revision `3`, but found it along `6` and `6a` that should differ only in value of `K`. I've added support for it along the way.

Thank you in advance for considering this enhancement.

### CODE REVIEW

**Comment by JustArchi** [comment]
Thanks a lot for merging!

If it's not too big of a hassle for you, I'd really appreciate a new nuget release with this feature in, so I could drop usage of my fork in the main project, of course once you're satisfied and ready with it. Thanks in advance! :sunglasses:

**Comment by yallie** [comment]
https://www.nuget.org/packages/srp/1.0.7

Done! :)

**Comment by JustArchi** [comment]
Thank you a lot @yallie, all the best! :partying_face:

**Comment by yallie** [comment]
Thanks for the PR! 🥇 

Out of curiosity, what's the name of the server that supports plain SRP-6 protocol?
Is it open-source? Or does it use an open-source library that can be listed as [compatible implementation](https://github.com/secure-remote-password/implementations)?

**Comment by JustArchi** [comment]
It's a proprietary third-party broker (stock market) service, there is a chance that they're using some open-source solution behind it, but I don't have the details about their exact implementation and I don't want to ask as I'm not directly connected with that company (just a guy who is writing integration with it). If you'd like to I can shoot you an e-mail with the URL if you want to pursue it further, but chance is it won't even reach the people who will be able to answer your question :slightly_frowning_face:. Sorry, I don't know.

**Comment by yallie** [comment]
Ah, nevermind, I was just asking. 
Never seen SRP-3 or SRP-6 implementations before, got curious :)

**Pull request merged**
